### ISSUE TITLE
「JR線」で省略する路線数を多めにする

### ISSUE THREAD

**Issue by TinyKitten** [TrainLCD/MobileApp#107]
いまJR線が2線あるだけで省略されてしまうが、少なすぎる気がする

**Comment by 10mocy** [comment]
5路線以上は短縮で良いのかも

**Comment by TinyKitten** [comment]
https://github.com/TinyKitten/TrainLCD/blob/dev/src/constants.ts#L34
https://github.com/TinyKitten/TrainLCD/blob/dev/src/utils/jr.ts#L28

コメントと実装が相反している。「以上」であれば`>=`ではなく`>`が自然。

**Comment by TinyKitten** [comment]
とりあえず３路線でテスト。多すぎると溢れてしまう

**Comment by TinyKitten** [comment]
私鉄４線以上もしくはJR線５線以上も良さそう
