### ISSUE TITLE
サービス全面再開

### ISSUE THREAD

**Issue by TinyKitten** [TrainLCD/MobileApp#1219]
- [x] 現存駅中韓対応100%
- [ ] ~首都圏・中京圏・京阪神圏のすべての優等列車に対応（せめてCSで来ていた名鉄優等対応）~
- [ ]  ~行き先と種別の選択を分離できるようにする~
- [x] ミラーリングシェアを隠す
  - リンクから起動できるのは防いでしまうとそもそも起動できないのでそのまま接続しちゃってもいい
  - むしろシェアしたリンクが開けないというストレスもありそうなので
- [ ] ~CSで来ていた名鉄優等・名鉄路線間直通対応~
  - 直通が多すぎるこれスコープに入れてたら一生公開できない
- [ ] ~JRWテーマをまともに使えるようにする~
  - 一旦開発者専用で隠す

**Comment by Sw-Saturn** [comment]
- 優等列車の対応
  - 地方で分けるよりは利用者数とかで優先度つけたほうがいいのかも

- 直通運転対応
  - どこを基準とするかは難しい
  - 空港アクセスに使われる路線とかは需要ありそうかも

**Comment by TinyKitten** [comment]
> 地方で分けるよりは利用者数とかで優先度つけたほうがいいのかも

これは実際にTrainLCDで使われてる人数って意味？

**Comment by Sw-Saturn** [comment]
> これは実際にTrainLCDで使われてる人数って意味？

そやね

**Comment by TinyKitten** [comment]
センシティブなデータは取ってないんだよなぁ...どうしようかな

**Comment by TinyKitten** [comment]
大体サービス再開日時は確定はしたが、まだ未公開にしたい

**Comment by TinyKitten** [comment]
大きなバグさえなければいつでも公開可能そう
