### ISSUE TITLE
路線選択画面の位置情報更新ボタンを長押しした際、タップのイベントがキャンセルされる

### ISSUE THREAD

**Issue by katabame** [TrainLCD/MobileApp#1414]
路線選択画面の位置情報更新ボタンを長押しし続けると、
色が薄くなる(選択状態)→色が濃ゆくなる(非選択状態)となり、
長押しを解除した際にボタンを押したことにならない

Ref: https://twitter.com/katabame/status/1523189759660924928

**Comment by katabame** [comment]
位置情報更新ボタンだけでなく、ボタン全般で発生する模様

**Comment by katabame** [comment]
![CBC24C21-985D-454E-AF1F-519478B92542](https://user-images.githubusercontent.com/9818101/168415620-ae3fc7a6-b494-4eaf-982c-e65b6753ecfa.png)
ここのボタンでは発生しない

**Comment by TinyKitten** [comment]
対応不要
