### ISSUE TITLE
乗り換え案内以外の画面でもスクロールが可能になっている可能性がある

### ISSUE THREAD

**Issue by katabame** [TrainLCD/MobileApp#1415]
停車駅が出ている画面で複数地点のタップを行うと、スクロール自体はできないが現在位置の赤と青のアニメーション等が停止する
Ref: https://twitter.com/katabame/status/1523191561668165632

**Comment by TinyKitten** [comment]
https://github.com/TrainLCD/MobileApp/issues/1348
こちらのチケットで対応中
