### ISSUE TITLE
長押ししている際にアニメーションで表示内容が切り替わると、複数ActionSheetが表示される

### ISSUE THREAD

**Issue by katabame** [TrainLCD/MobileApp#1416]
ただいま〇〇の部分をアニメーションで切り替わる直前ぐらいに長押しを開始し、
モーダルが出る前に表示内容が切り替わると、
長押しを継続したまま他の場所(〇〇行)などをタップした際にモーダルが複数表示される

また、おそらくそれに起因したモーダルの表示位置が画面隅になるなどを確認している

Ref: https://twitter.com/katabame/status/1523193299606990849
https://twitter.com/katabame/status/1523194841076670465

**Comment by katabame** [comment]
ビルド439で再現
ActionSheetが複数表示された直後に長押しを解除すると全てのActionSheetの表示が消えるが、
複数表示後も長押しし続けると長押し解除しても残り続ける。
(恐らく3個目を表示しようとするが表示できていない？)

また、複数表示された状態でミラーリングシェアを選択すると表示されず、以降長押ししてもActiomSheetが表示されなくなる。

**Comment by katabame** [comment]
複数表示された状態で、何かしらを選択(ミラーリングシェア以外も)すると、動作しているように見えるが、次に路線図画面に遷移した際に表示が切り替わらない、長押しが効かないなどが発生する

この状態で長押しを複数回行い、バックグラウンドにアプリを回して復帰するとActionSheetが位置がずれた状態で表示される？

**Comment by katabame** [comment]
![Uploading 87340AF3-5147-40A8-8516-FE92D626EEA0.png…]()

**Comment by katabame** [comment]
![207F0EA1-FDA1-40B8-8A2A-ACAE8D9989DC](https://user-images.githubusercontent.com/9818101/168415981-26826c49-af50-4111-9b5b-fcd5671deb02.png)

**Comment by TinyKitten** [comment]
アプリが重い時にのみに発生しそうなのと極端に重くなるような実装は今の所なくなったのでClose
